### ISSUE TITLE
Adjusting TTL & HL via Termux:boot - iptables commands errors "No chain/target/match by that name."

### ISSUE THREAD

**Issue by biggestcookie** [nermur/no-tethering-restrictions#1]
Termux output:
![image](https://user-images.githubusercontent.com/5748299/136589486-ec45064b-a32b-4e4f-86b8-7fc7d56b5756.png)

**Comment by Iazos** [comment]
I can't test anything with root on the device I use, it would have been automated via Bash if so; compromise is I've changed the commands to assume less.
Now it's running a command to see what network interfaces are active, then changing the iptables commands 
yourself accordingly.
